/**
 * Copyright 2017 Workfront
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export type TObjCode = "ACSLVL" | "ALVPER" | "ACSREQ" | "ACSRUL" | "ARPREF" | "ACSCP" | "ASCPAT" | "ACSTOK" | "ACNTRP" | "ACK" | "AGILEV" | "ANCMNT" | "ANMATT" | "AMNTO" | "ANCREC" | "APPBLD" | "APEVT" | "APGLOB" | "APPINF" | "APPROVAL" | "ARVPTH" | "ARVPRC" | "APRPROCATCH" | "ARVSTP" | "ARVSTS" | "ASSGN" | "AUDS" | "AUTH" | "AVATAR" | "AWAPVL" | "BKGJOB" | "BLIN" | "BSTSK" | "BILL" | "BRND" | "BDNEVT" | "CALEVT" | "CALITM" | "CALEND" | "CALPTL" | "CALSEC" | "CALEXP" | "LTMPLC" | "CTGY" | "CATACR" | "CTCSRL" | "CTCSRM" | "CTGYPA" | "CTGPEX" | "CMPY" | "CMPSRV" | "CPPRED" | "CXTHP" | "CSTEM" | "CSTEMO" | "LTMCL" | "CSTMNU" | "CMSCMS" | "CSTQRT" | "CUST" | "CUSDEL" | "CSFD" | "CUSTPR" | "CPTC" | "CSTSEC" | "DMETAL" | "DMETAG" | "DOCFLD" | "DOCU" | "DOCAPL" | "DOCFDR" | "DOCPRO" | "DOCCFG" | "DOCMET" | "DOCREQ" | "DOCSHR" | "DOCTSK" | "DOCV" | "EMAILC" | "EMLTPL" | "ENDR" | "ENDSHR" | "EVNTH" | "EVTSUB" | "EWS" | "EXRATE" | "EXPNS" | "EXPTYP" | "EXTDOC" | "EXTSEC" | "FVRITE" | "FEATR" | "FINDAT" | "GROUP" | "HOUR" | "HOURT" | "IPRAGE" | "IROW" | "ITMPL" | "IDDI" | "ITRN" | "JRNLE" | "JRNLF" | "KSS" | "LYTMPL" | "LTMPDP" | "LTMPLP" | "LICEOR" | "LIKE" | "LNKFDR" | "MTSK" | "MSGARG" | "PRSTOBJ" | "MILE" | "MPATH" | "MOBILDVC" | "NONWKD" | "NOTE" | "NTAG" | "NOTPRF" | "TMNR" | "OBJCAT" | "OPTASK" | "PARAM" | "PRMDTX" | "PGRP" | "POPT" | "PVAL" | "POPA" | "PTLPFL" | "PTLSEC" | "PTLTAB" | "PRTBSC" | "PORT" | "PRED" | "PROSET" | "PCPREF" | "PRGM" | "PROJ" | "PRTU" | "PTEAM" | "PROOF" | "PRFAPL" | "QUED" | "QUET" | "QUETGP" | "RATE" | "RECENT" | "RECENTMENUITEM" | "RUPDTE" | "RECR" | "RMVDOV" | "RPTFDR" | "RSELR" | "RESVT" | "RSALLO" | "RSCONT" | "RESMGR" | "RSPOOL" | "RSPL" | "RSFT" | "RSTOBJ" | "RISK" | "RSKTYP" | "ROLE" | "RRUL" | "S3MT" | "SSOMAP" | "SSOMR" | "SSOPT" | "SSOUSR" | "SNDMG" | "SCHED" | "SCHREP" | "SCORE" | "SCANS" | "SCOPT" | "SCOREQ" | "SRCEVT" | "SECANC" | "SEQ" | "SHRSET" | "SPAPVR" | "TASK" | "TEAMOB" | "TEAMMB" | "TEAMMR" | "TMPL" | "TASSGN" | "TPRED" | "TTSK" | "TMTU" | "TTEAM" | "TMNOT" | "TSHET" | "TSPRO" | "TSHTMP" | "UIFT" | "UIGB" | "UITMPL" | "UIVW" | "UPDATE" | "USER" | "USERAC" | "USRAVL" | "USRDEL" | "USRGPS" | "USRNOT" | "USOP" | "USERPF" | "USERRS" | "USRSEC" | "WORK" | "WRKITM"

export declare const AccessLevel: TObjCode
export declare const AccessLevelPermissions: TObjCode
export declare const AccessRequest: TObjCode
export declare const AccessRule: TObjCode
export declare const AccessRulePreference: TObjCode
export declare const AccessScope: TObjCode
export declare const AccessScopeAction: TObjCode
export declare const AccessToken: TObjCode
export declare const AccountRep: TObjCode
export declare const Acknowledgement: TObjCode
export declare const AgileView: TObjCode
export declare const Announcement: TObjCode
export declare const AnnouncementAttachment: TObjCode
export declare const AnnouncementOptOut: TObjCode
export declare const AnnouncementRecipient: TObjCode
export declare const AppBuild: TObjCode
export declare const AppEvent: TObjCode
export declare const AppGlobal: TObjCode
export declare const AppInfo: TObjCode
export declare const Approval: TObjCode
export declare const ApprovalPath: TObjCode
export declare const ApprovalProcess: TObjCode
export declare const ApprovalProcessAttachable: TObjCode
export declare const ApprovalStep: TObjCode
export declare const ApproverStatus: TObjCode
export declare const Assignment: TObjCode
export declare const AuditLoginAsSession: TObjCode
export declare const Authentication: TObjCode
export declare const Avatar: TObjCode
export declare const AwaitingApproval: TObjCode
export declare const BackgroundJob: TObjCode
export declare const Baseline: TObjCode
export declare const BaselineTask: TObjCode
export declare const BillingRecord: TObjCode
export declare const Branding: TObjCode
export declare const BurndownEvent: TObjCode
export declare const CalendarEvent: TObjCode
export declare const CalendarFeedEntry: TObjCode
export declare const CalendarInfo: TObjCode
export declare const CalendarPortalSection: TObjCode
export declare const CalendarSection: TObjCode
export declare const CallableExpression: TObjCode
export declare const CardField: TObjCode
export declare const Category: TObjCode
export declare const CategoryAccessRule: TObjCode
export declare const CategoryCascadeRule: TObjCode
export declare const CategoryCascadeRuleMatch: TObjCode
export declare const CategoryParameter: TObjCode
export declare const CategoryParameterExpression: TObjCode
export declare const Company: TObjCode
export declare const ComponentKey: TObjCode
export declare const ContextSensitiveHelp: TObjCode
export declare const CrossProjectPredecessor: TObjCode
export declare const CustomEnum: TObjCode
export declare const CustomEnumOrder: TObjCode
export declare const CustomLabel: TObjCode
export declare const CustomMenu: TObjCode
export declare const CustomMenuCustomMenu: TObjCode
export declare const CustomQuarter: TObjCode
export declare const Customer: TObjCode
export declare const CustomerDeletion: TObjCode
export declare const CustomerFeedback: TObjCode
export declare const CustomerPreferences: TObjCode
export declare const CustomerTimelineCalc: TObjCode
export declare const CustsSections: TObjCode
export declare const DocMetadataLink: TObjCode
export declare const DocMetadataLinkGroup: TObjCode
export declare const DocsFolders: TObjCode
export declare const Document: TObjCode
export declare const DocumentApproval: TObjCode
export declare const DocumentFolder: TObjCode
export declare const DocumentProvider: TObjCode
export declare const DocumentProviderConfig: TObjCode
export declare const DocumentProviderMetadata: TObjCode
export declare const DocumentRequest: TObjCode
export declare const DocumentShare: TObjCode
export declare const DocumentTaskStatus: TObjCode
export declare const DocumentVersion: TObjCode
export declare const Email: TObjCode
export declare const EmailTemplate: TObjCode
export declare const Endorsement: TObjCode
export declare const EndorsementShare: TObjCode
export declare const EventHandler: TObjCode
export declare const EventSubscription: TObjCode
export declare const EwsFileHandle: TObjCode
export declare const ExchangeRate: TObjCode
export declare const Expense: TObjCode
export declare const ExpenseType: TObjCode
export declare const ExternalDocument: TObjCode
export declare const ExternalSection: TObjCode
export declare const Favorite: TObjCode
export declare const Feature: TObjCode
export declare const FinancialData: TObjCode
export declare const Group: TObjCode
export declare const Hour: TObjCode
export declare const HourType: TObjCode
export declare const IPRange: TObjCode
export declare const ImportRow: TObjCode
export declare const ImportTemplate: TObjCode
export declare const InstalledDDItem: TObjCode
export declare const Iteration: TObjCode
export declare const JournalEntry: TObjCode
export declare const JournalField: TObjCode
export declare const KickStart: TObjCode
export declare const LayoutTemplate: TObjCode
export declare const LayoutTemplateDatePreference: TObjCode
export declare const LayoutTemplatePage: TObjCode
export declare const LicenseOrder: TObjCode
export declare const Like: TObjCode
export declare const LinkedFolder: TObjCode
export declare const MasterTask: TObjCode
export declare const MessageArg: TObjCode
export declare const MetaRecord: TObjCode
export declare const Milestone: TObjCode
export declare const MilestonePath: TObjCode
export declare const MobileDevice: TObjCode
export declare const NonWorkDay: TObjCode
export declare const Note: TObjCode
export declare const NoteTag: TObjCode
export declare const NotificationPreference: TObjCode
export declare const NotificationRecord: TObjCode
export declare const ObjectCategory: TObjCode
export declare const OpTask: TObjCode
export declare const Parameter: TObjCode
export declare const ParameterDescriptiveText: TObjCode
export declare const ParameterGroup: TObjCode
export declare const ParameterOption: TObjCode
export declare const ParameterValue: TObjCode
export declare const PopAccount: TObjCode
export declare const PortalProfile: TObjCode
export declare const PortalSection: TObjCode
export declare const PortalTab: TObjCode
export declare const PortalTabSection: TObjCode
export declare const Portfolio: TObjCode
export declare const Predecessor: TObjCode
export declare const Preference: TObjCode
export declare const PrivateCustomerPref: TObjCode
export declare const Program: TObjCode
export declare const Project: TObjCode
export declare const ProjectUser: TObjCode
export declare const ProjectUserRole: TObjCode
export declare const Proof: TObjCode
export declare const ProofApproval: TObjCode
export declare const QueueDef: TObjCode
export declare const QueueTopic: TObjCode
export declare const QueueTopicGroup: TObjCode
export declare const Rate: TObjCode
export declare const Recent: TObjCode
export declare const RecentMenuItem: TObjCode
export declare const RecentUpdate: TObjCode
export declare const RecurrenceRule: TObjCode
export declare const RemovedDocumentVersion: TObjCode
export declare const ReportFolder: TObjCode
export declare const Reseller: TObjCode
export declare const ReservedTime: TObjCode
export declare const ResourceAllocation: TObjCode
export declare const ResourceContour: TObjCode
export declare const ResourceManager: TObjCode
export declare const ResourcePool: TObjCode
export declare const RsrcPool: TObjCode
export declare const ResourceSchedulingFilter: TObjCode
export declare const RestorableObject: TObjCode
export declare const Risk: TObjCode
export declare const RiskType: TObjCode
export declare const Role: TObjCode
export declare const RoutingRule: TObjCode
export declare const S3Migration: TObjCode
export declare const SSOMapping: TObjCode
export declare const SSOMappingRule: TObjCode
export declare const SSOOption: TObjCode
export declare const SSOUsername: TObjCode
export declare const SandboxMigration: TObjCode
export declare const Schedule: TObjCode
export declare const ScheduledReport: TObjCode
export declare const ScoreCard: TObjCode
export declare const ScoreCardAnswer: TObjCode
export declare const ScoreCardOption: TObjCode
export declare const ScoreCardQuestion: TObjCode
export declare const SearchEvent: TObjCode
export declare const SecurityAncestor: TObjCode
export declare const Sequence: TObjCode
export declare const SharingSettings: TObjCode
export declare const StepApprover: TObjCode
export declare const Task: TObjCode
export declare const Team: TObjCode
export declare const TeamMember: TObjCode
export declare const TeamMemberRole: TObjCode
export declare const Template: TObjCode
export declare const TemplateAssignment: TObjCode
export declare const TemplatePredecessor: TObjCode
export declare const TemplateTask: TObjCode
export declare const TemplateUser: TObjCode
export declare const TemplateUserRole: TObjCode
export declare const TimedNotification: TObjCode
export declare const Timesheet: TObjCode
export declare const TimesheetProfile: TObjCode
export declare const TimesheetTemplate: TObjCode
export declare const UIFilter: TObjCode
export declare const UIGroupBy: TObjCode
export declare const UITemplate: TObjCode
export declare const UIView: TObjCode
export declare const Update: TObjCode
export declare const User: TObjCode
export declare const UserActivity: TObjCode
export declare const UserAvailability: TObjCode
export declare const UserDelegation: TObjCode
export declare const UserGroups: TObjCode
export declare const UserNote: TObjCode
export declare const UserObjectPref: TObjCode
export declare const UserPrefValue: TObjCode
export declare const UserResource: TObjCode
export declare const UsersSections: TObjCode
export declare const Work: TObjCode
export declare const WorkItem: TObjCode
